DROP TABLE IF EXISTS Categories CASCADE;
DROP TABLE IF EXISTS Products CASCADE;
DROP TABLE IF EXISTS CategoryProducts CASCADE;

CREATE TABLE Categories (
    CategoryId SERIAL PRIMARY KEY,
    Name TEXT,
    Description TEXT,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE Products (
    ProductId SERIAL PRIMARY KEY,
    Name TEXT,
    Description TEXT,
    Brand TEXT,
    Price REAL,
    Stock INTEGER,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE CategoryProducts
(
    CategoryProductsId SERIAL PRIMARY KEY,
    CategoryId INT REFERENCES Categories(CategoryId) NOT NULL,
    ProductId INT REFERENCES Products(ProductId) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);
