ALTER TABLE IF EXISTS UserClaims DROP CONSTRAINT IF EXISTS userclaims_userid_fkey;
ALTER TABLE IF EXISTS UserLogins DROP CONSTRAINT IF EXISTS userlogins_userid_fkey;
ALTER TABLE IF EXISTS UserRoles DROP CONSTRAINT IF EXISTS userroles_userid_fkey;
ALTER TABLE IF EXISTS UserTokens DROP CONSTRAINT IF EXISTS usertokens_userid_fkey;
ALTER TABLE IF EXISTS UserAddresses DROP CONSTRAINT IF EXISTS useraddresses_userid_fkey;
ALTER TABLE IF EXISTS UserTelephones DROP CONSTRAINT IF EXISTS usertelephones_userid_fkey;

DROP TABLE IF EXISTS UserRoles CASCADE;
DROP TABLE IF EXISTS UserClaims CASCADE;
DROP TABLE IF EXISTS UserTokens CASCADE;
DROP TABLE IF EXISTS UserLogins CASCADE;
DROP TABLE IF EXISTS UserAddresses CASCADE;
DROP TABLE IF EXISTS UserTelephones CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Roles CASCADE;
DROP TABLE IF EXISTS Addresses CASCADE;
DROP TABLE IF EXISTS Telephones CASCADE;
DROP TABLE IF EXISTS Claims CASCADE;
DROP TABLE IF EXISTS Tokens CASCADE;
DROP TABLE IF EXISTS Logins CASCADE;

CREATE TABLE Roles
(
    RoleId SERIAL PRIMARY KEY,
    RoleName VARCHAR(256) NOT NULL UNIQUE,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true,
    
    CONSTRAINT UQ_RoleNameValue UNIQUE (RoleName)
);

CREATE TABLE Claims
(
    ClaimId SERIAL PRIMARY KEY,
    ClaimType VARCHAR(256) NOT NULL,
    ClaimValue VARCHAR(256) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT UQ_ClaimTypeValue UNIQUE (ClaimType, ClaimValue)
);

CREATE TABLE Tokens
(
    TokenId SERIAL PRIMARY KEY,
    TokenValue VARCHAR(1024) NOT NULL UNIQUE,
    TokenType VARCHAR(128) NOT NULL,
    Expires TIMESTAMPTZ NOT NULL,
    Message VARCHAR(128) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE Logins
(
    LoginId SERIAL PRIMARY KEY,
    LoginProvider VARCHAR(128),
    ProviderKey VARCHAR(128),
    RequestIdentifier VARCHAR(512),
    ActionType VARCHAR(128),
    IpAddressess VARCHAR(128),
    UserAgent VARCHAR(128),
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);
	
CREATE TABLE Addresses
(
    AddressId SERIAL PRIMARY KEY,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(50) NOT NULL,
    ZipCode VARCHAR(20) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE Telephones
(
    TelephoneId SERIAL PRIMARY KEY,
    PhoneNumber VARCHAR(20) NOT NULL,
    PhoneType VARCHAR(50) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE Users
(
    UserId SERIAL PRIMARY KEY,
    UserName VARCHAR(256) NOT NULL UNIQUE,
    Name VARCHAR(256) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    DateOfBirth DATE NOT NULL,
    Gender VARCHAR(1) NOT NULL,
    Email VARCHAR(256) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    SecurityStamp VARCHAR(255),
    TwoFactorEnabled BOOLEAN NOT NULL,
    LockoutEndDateUtc TIMESTAMPTZ,
    LockoutEnabled BOOLEAN NOT NULL,
    AccessFailedCount INT NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE UserAddresses
(
    Id SERIAL PRIMARY KEY,
    UserId INT REFERENCES Users(UserId) NOT NULL,
    AddressId INT REFERENCES Addresses(AddressId) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE UserTelephones
(
    Id SERIAL PRIMARY KEY,
    UserId INT REFERENCES Users(UserId) NOT NULL,
    TelephoneId INT REFERENCES Telephones(TelephoneId) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE UserRoles
(
    UserRoleId SERIAL PRIMARY KEY,
    UserId INT REFERENCES Users(UserId) NOT NULL,
    RoleId INT REFERENCES Roles(RoleId) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE UserClaims
(
    UserClaimId SERIAL PRIMARY KEY,
    UserId INT REFERENCES Users(UserId) NOT NULL,
    ClaimId INT REFERENCES Claims(ClaimId) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE UserTokens
(
    UserTokenId SERIAL PRIMARY KEY,
    UserId INT REFERENCES Users(UserId) NOT NULL,
    TokenId INT REFERENCES Tokens(TokenId) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE UserLogins
(
    UserLoginId SERIAL PRIMARY KEY,
    UserId INT REFERENCES Users(UserId) NOT NULL,
    LoginId INT REFERENCES Logins(LoginId) NOT NULL,
    CreatedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModifiedDate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT true
);
